### ISSUE TITLE
유저 리스트 조회 API에서 아이디 검색이 불안정하고, 응답 스키마가 몇개 없는 문제

### ISSUE THREAD

**Issue by jadru** [Media-XI/art-platform-backend#62]
![image](https://github.com/Media-XI/art-platform-backend/assets/21021930/c631a3be-b6f6-447e-bed8-17b75c1979ff)
- user-어쩌고 하는 아이디가 많은데 user로 조회하니 아무것도 안나오는 문제
- 응답 스키마가 username, userPicture, companyName만 있는 문제
  - 해당 사항은 username, name, picture, companyName, companyRole, Role까지 추가 부탁합니다.

**Comment by haroya01** [comment]
https://github.com/Media-XI/art-platform-backend/pull/67 해결됬습니다
